//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Blackducksoftware.Integration.Hub.Nuget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Blackducksoftware.Integration.Hub.Nuget.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;packages&gt;
        ///  &lt;package id=&quot;Microsoft.Web.Xdt&quot; version=&quot;2.1.1&quot; targetFramework=&quot;net452&quot; /&gt;
        ///  &lt;package id=&quot;Newtonsoft.Json&quot; version=&quot;9.0.1&quot; targetFramework=&quot;net452&quot; /&gt;
        ///  &lt;package id=&quot;NuGet.Client&quot; version=&quot;3.5.0&quot; targetFramework=&quot;net452&quot; /&gt;
        ///  &lt;package id=&quot;NuGet.Commands&quot; version=&quot;3.5.0&quot; targetFramework=&quot;net452&quot; /&gt;
        ///  &lt;package id=&quot;NuGet.Common&quot; version=&quot;3.5.0&quot; targetFramework=&quot;net452&quot; /&gt;
        ///  &lt;package id=&quot;NuGet.Configuration&quot; version=&quot;3.5.0&quot; targetFramework=&quot;net452&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;specVersion&quot;: &quot;1.1.0&quot;,
        ///    &quot;@id&quot;: &quot;uuid:4f12abf6-f105-4546-b9c8-83c98a8611c5&quot;,
        ///    &quot;@type&quot;: &quot;BillOfMaterials&quot;,
        ///    &quot;name&quot;: &quot;BuildBomTask Black Duck I/O Export&quot;,
        ///    &quot;relationship&quot;: []
        ///  },
        ///  {
        ///    &quot;revision&quot;: &quot;0.0.1&quot;,
        ///    &quot;@id&quot;: &quot;data:BuildBomTask/0.0.1&quot;,
        ///    &quot;@type&quot;: &quot;Project&quot;,
        ///    &quot;name&quot;: &quot;BuildBomTask&quot;,
        ///    &quot;externalIdentifier&quot;: {
        ///      &quot;externalSystemTypeId&quot;: &quot;nuget&quot;,
        ///      &quot;externalId&quot;: &quot;BuildBomTask/0.0.1&quot;
        ///    },
        ///    &quot;relationship&quot;: []
        ///  },
        ///  {
        ///    &quot;revision&quot;: &quot;2.1.1&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_bdio {
            get {
                return ResourceManager.GetString("sample_bdio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Web.Xdt/2.1.1
        ///Newtonsoft.Json/9.0.1
        ///NuGet.Client/3.5.0
        ///NuGet.Commands/3.5.0
        ///NuGet.Common/3.5.0
        ///NuGet.Configuration/3.5.0
        ///NuGet.ContentModel/3.5.0
        ///NuGet.Core/2.14.0
        ///NuGet.DependencyResolver/3.5.0
        ///NuGet.DependencyResolver.Core/3.5.0
        ///NuGet.Frameworks/3.5.0
        ///NuGet.LibraryModel/3.5.0
        ///NuGet.PackageManagement/3.5.0
        ///NuGet.Packaging/3.5.0
        ///NuGet.Packaging.Core/3.5.0
        ///NuGet.Packaging.Core.Types/3.5.0
        ///NuGet.ProjectManagement/3.5.0
        ///NuGet.ProjectModel/3.5.0
        ///NuGet.Protocol.Core.Types/3.5.0
        ///NuGet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_flat {
            get {
                return ResourceManager.GetString("sample_flat", resourceCulture);
            }
        }
    }
}
