install:
    - nuget restore

build:
  project: hub-nuget.sln
  verbosity: detailed
  
on_success:  
- nuget install Hub-NuGet
- cmd: Hub-NuGet.1.0.0\tools\buildBom.exe --hub_deploy_bdio=false --excluded_modules=integration-bdio.NET-test -v
- curl -s https://test.duckbuild.io/batch/appveyor > appveyor.bat
- appveyor
