install:
    - nuget restore

build:
  project: hub-nuget.sln
  verbosity: detailed
  
on_success:
- nuget install Hub-Nuget -Version 1.1.0
- Hub-NuGet.1.1.0\tools\buildBom.exe --hub_deploy_bdio=false --hub_create_merged_bdio=true
- curl -s https://copilot.blackducksoftware.com/batch/appveyor > appveyor.bat
- appveyor
