install:
    - nuget restore

build:
  project: hub-nuget.sln
  verbosity: detailed

environment:
  my_variable:
    secure: v6/PPE4nIxNrzJRi7gxB2q6bBGRBwPjUZ4hF/LUv+Hc=
    
after_test: 
# generate report for NUnit testing framework:
    - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single BuildBomTaskTest/obj/Debug/BuildBomTaskTest.dll" -output:coverage.xml
    - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
