//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Blackducksoftware.Integration.Hub.Common.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Blackducksoftware.Integration.Hub.Common.Net.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hub_BD_logo {
            get {
                object obj = ResourceManager.GetObject("Hub_BD_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .riskReportBackgroundColor {
        ///	background-color: rgb(255,255,255);
        ///}
        ///
        ///.riskReportText, .linkText, .h1, .riskSummaryContainerLabel, .riskSummaryLabel, .riskSummaryCount, .risk-count, .table-summary,.versionSummaryLabel, .summaryLabel,.versionSummaryLargeLabel, .summaryValue, .columnLabel, .riskColumnLabel, .licenseColumn, .riskColumn, .componentColumn, .clickable {
        ///	text-align: left;
        ///	font-family: &apos;Open Sans&apos;, sans-serif;
        ///	font-size: 14px;
        ///	color: #000;
        ///}
        ///
        ///.hidden {
        ///	display: none;
        ///}
        ///
        ///.violation {
        ///	color: #9c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HubBomReport {
            get {
                return ResourceManager.GetString("HubBomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Hub Common
        /// *
        /// * Copyright (C) 2017 Black Duck Software, Inc.
        /// * http://www.blackducksoftware.com/
        /// *
        /// * Licensed to the Apache Software Foundation (ASF) under one
        /// * or more contributor license agreements. See the NOTICE file
        /// * distributed with this work for additional information
        /// * regarding copyright ownership. The ASF licenses this file
        /// * to you under the Apache License, Version 2.0 (the
        /// * &quot;License&quot;); you may not use this file except in compliance
        /// * with the License. You may obtain a copy of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HubBomReportFunctions {
            get {
                return ResourceManager.GetString("HubBomReportFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Hub Common
        /// *
        /// * Copyright (C) 2017 Black Duck Software, Inc.
        /// * http://www.blackducksoftware.com/
        /// *
        /// * Licensed to the Apache Software Foundation (ASF) under one
        /// * or more contributor license agreements. See the NOTICE file
        /// * distributed with this work for additional information
        /// * regarding copyright ownership. The ASF licenses this file
        /// * to you under the Apache License, Version 2.0 (the
        /// * &quot;License&quot;); you may not use this file except in compliance
        /// * with the License. You may obtain a copy of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HubRiskReport {
            get {
                return ResourceManager.GetString("HubRiskReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Hub Common
        /// *
        /// * Copyright (C) 2017 Black Duck Software, Inc.
        /// * http://www.blackducksoftware.com/
        /// *
        /// * Licensed to the Apache Software Foundation (ASF) under one
        /// * or more contributor license agreements. See the NOTICE file
        /// * distributed with this work for additional information
        /// * regarding copyright ownership. The ASF licenses this file
        /// * to you under the Apache License, Version 2.0 (the
        /// * &quot;License&quot;); you may not use this file except in compliance
        /// * with the License. You may obtain a copy of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_3_1_1_min {
            get {
                return ResourceManager.GetString("jquery_3_1_1_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///	   &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	   &lt;title&gt;Hub Risk Report&lt;/title&gt;
        ///	   &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/HubBomReport.css&quot;/&gt;
        ///	   &lt;link rel=&quot;stylesheet&quot; href=&quot;https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css&quot;&gt;
        ///	   &lt;script src=&quot;js/jquery-3.1.1.min.js&quot;&gt;&lt;/script&gt;
        ///	   &lt;script src=&quot;js/HubBomReportFunctions.js&quot;&gt;&lt;/script&gt;
        ///	   &lt;script src=&quot;js/HubRiskReport.js&quot;&gt;&lt;/script&gt;
        ///	   &lt;script src=&quot;js/Sortable.js&quot;&gt;&lt;/script&gt;
        ///	   &lt;script type=&quot;text/javascr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string riskreport {
            get {
                return ResourceManager.GetString("riskreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Hub Common
        /// *
        /// * Copyright (C) 2017 Black Duck Software, Inc.
        /// * http://www.blackducksoftware.com/
        /// *
        /// * Licensed to the Apache Software Foundation (ASF) under one
        /// * or more contributor license agreements. See the NOTICE file
        /// * distributed with this work for additional information
        /// * regarding copyright ownership. The ASF licenses this file
        /// * to you under the Apache License, Version 2.0 (the
        /// * &quot;License&quot;); you may not use this file except in compliance
        /// * with the License. You may obtain a copy of  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sortable {
            get {
                return ResourceManager.GetString("Sortable", resourceCulture);
            }
        }
    }
}
